dfondation = {
    "SOI" : {
        "role": "DFONDATION_SCOLAIRE",
        "schema": "AFFAIRES_SCOLAIRE_SOI",
        "tables": {
            "DIM_DESCRIPTEUR" : "CATEGORIE_DESCRIPTION,CATEGORIE_TYPE_CODE,CATEGORIE_TYPE_DESCRIPTION,DESCRIPTEUR_CODE,DESCRIPTEUR_DESCRIPTION,DESCRIPTEUR_ID,NATURE_CODE,NATURE_DESCRIPTION,ORDRE_ENSEIGNEMENT_CODE,ORDRE_ENSEIGNEMENT_DESCRIPTION",
            "DIM_GROUPE" : "GROUPE_ID,GROUPE_CODE,ANNEE_SCOLAIRE,GROUPE_NOM,GROUPE_DESCRIPTION,GROUPE_TYPE,GROUPE_NOM_CODE,GROUPE_NOM_NO",
            "FAIT_INTERVENTION" : "INTERVENTION_ID,ECOLE_ID,ELEVE_ID,DOSSIER_ID,ETAPE_ID,TEMPS_ID,DESCRIPTEUR_ID,GROUPE_ID,EMPLOYE_ID,FICHE,ETABLISSEMENT_TYPE,INTERVENTION_CLE_NATURELLE,PARTAGE_ELEVES_IND,PARTAGE_PARENTS_IND,CREATION_HEURE,ASSIGNATION_GROUPE_COMPLET_IND,INFORMATIONS_COMPLEMENTAIRES,OBSERVATIONS_LIEES",
            "FAIT_OBSERVATION" : "OBSERVATION_ID,FICHE,OBSERVATION_CLE_NATURELLE,ECOLE_ID,ELEVE_ID,DOSSIER_ID,ETAPE_ID,TEMPS_ID,DESCRIPTEUR_ID,GROUPE_ID,EMPLOYE_ID,ETABLISSEMENT_TYPE,PARTAGE_ELEVES_IND,PARTAGE_PARENTS_IND,CREATION_HEURE,ASSIGNATION_GROUPE_COMPLET_IND,INFORMATIONS_COMPLEMENTAIRES"
        }
    },
    "SCO" : {
        "role": "DFONDATION_SCOLAIRE",
        "schema": "AFFAIRES_SCOLAIRE",
        "tables": {
            "DIM_ELEVE" : "ELEVE_ID,CODE_UNIQUE_ELEVE,FICHE,CODE_PERMANENT",
            "DIM_DOSSIER" : "ELEVE_ID,ANNEE,ECOLE_CODE,FICHE"
        }
    }

}